baseURL = "https://algo-afro-futures.lurk.org/"
languageCode = "en-us"
title = "(Algo|Afro) Futures"
theme = "hugo-researcher"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Apply"
    url = "/apply"
    weight = 3
  [[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 4
  [[menu.main]]
    name = "2023"
    url = "/2023-programme/"
    weight = 5
  [[menu.main]]
    name = "2022"
    url = "/2022-programme/"
    weight = 6
  [[menu.main]]
    name = "2021"
    url = "/2021-programme/"
    weight = 7
[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
