baseURL = "https://algo-afro-futures.lurk.org/"
languageCode = "en-us"
title = "(Algo|Afro) Futures"
theme = "hugo-researcher"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Apply"
    url = "/apply"
    weight = 3
  [[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 4
  [[menu.main]]
    name = "Mentoring Programme"
    url = "/mentoring-programme"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
