baseURL = "https://algo-afro-futures.lurk.org/"
languageCode = "en-us"
title = "(Algo|Afro) Futures"
theme = "hugo-researcher"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Apply"
    url = "/apply"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 3
  [[menu.main]]
    name = "2022 Artists"
    url = "/artists"
    weight = 4
  [[menu.main]]
    name = "2021 Artists"
    url = "/2021-artists"
    weight = 5
  [[menu.main]]
    name = "Mentors"
    url = "/mentors"
    weight = 6
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 7

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
