name = "Researcher"
license = "GPL-3.0"
licenselink = "https://github.com/ojroques/hugo-researcher/blob/master/LICENSE"
description = "A simple monospaced resume theme for Hugo."
tags = ["blog", "bootstrap", "clean", "minimal", "personal", "responsive", "resume", "simple"]
features = ["bootstrap", "responsive", "simple"]
homepage = "https://github.com/ojroques/hugo-researcher"
min_version = "0.74.3"

[author]
  name = "Olivier Roques"
  homepage = "https://oroques.dev/"

[original]
  author = "Ankit Sultana"
  homepage = "https://github.com/ankitsultana"
  repo = "https://github.com/ankitsultana/researcher"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/about"
    weight = 1
  [[menu.main]]
    name = "Application"
    url = "/resume.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    pre = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3
